In [1]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np
import pickle
import copy
import matplotlib.pyplot as plt
from sklearn.externals import joblib

from sklearn import preprocessing
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [3]:
path_temp = r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Dataset/Processed_Datasets/bert_cls_embeddings_df.pkl"
f = open(path_temp,'rb')
bert_cls_embeddings_df = pickle.load(f)
f.close()

path_temp = r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Dataset/Processed_Datasets/bert_cls_embeddings_text_df.pkl"
f = open(path_temp,'rb')
bert_cls_embeddings_text_df = pickle.load(f)
f.close()

path_temp = r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Dataset/Processed_Datasets/bert_cls_embeddings_text_user_df.pkl"
f = open(path_temp,'rb')
bert_cls_embeddings_text_user_df = pickle.load(f)
f.close()

In [4]:
bert_cls_embeddings_df            = bert_cls_embeddings_df.drop(['tweet_id'],axis=1)
bert_cls_embeddings_text_df       = bert_cls_embeddings_text_df.drop(['tweet_id'],axis=1)
bert_cls_embeddings_text_user_df  = bert_cls_embeddings_text_user_df.drop(['tweet_id'],axis=1)

In [5]:
bert_cls_embeddings_df

0         1         2  ...       766       767  label
0   -0.905121  0.696438 -0.410108  ...  0.170637 -0.138473      0
1    0.689706  0.642599  0.444143  ... -0.369758  0.030639      0
2   -0.061979  0.294637  1.001708  ... -0.114903 -0.023173      0
3   -0.130727  0.846263 -0.153783  ...  0.108040 -0.167144      0
4    0.065145  1.240352  1.072927  ... -0.130259  0.039278      1
..        ...       ...       ...  ...       ...       ...    ...
499 -0.661810  0.841780 -0.928869  ...  0.676775 -0.046627      1
500 -0.172682  0.684955 -0.278624  ... -0.358695 -0.151222      1
501 -0.128297  0.746526 -0.027099  ... -0.845969 -0.109107      0
502 -0.183494  0.869744 -0.316664  ...  0.654700  0.121160      1
503  0.159141  0.676894  0.825030  ... -0.264739  0.045607      1

[504 rows x 769 columns]

In [6]:
bert_cls_embeddings_text_df

0         1  ...  number_of_exclamation_marks  label
0   -0.905121  0.696438  ...                            0      0
1    0.689706  0.642599  ...                            0      0
2   -0.061979  0.294637  ...                            1      0
3   -0.130727  0.846263  ...                            0      0
4    0.065145  1.240352  ...                            0      1
..        ...       ...  ...                          ...    ...
486 -0.176294  1.212596  ...                            0      0
487 -0.661810  0.841780  ...                            0      1
488 -0.172682  0.684955  ...                            0      1
489 -0.128297  0.746526  ...                            0      0
490 -0.183494  0.869744  ...                            0      1

[491 rows x 779 columns]

In [7]:
bert_cls_embeddings_text_user_df

0         1  ...  follower_friends_ratio  label
0   -0.905121  0.696438  ...                5.546948      0
1    0.689706  0.642599  ...             2157.181818      0
2   -0.061979  0.294637  ...                1.008205      0
3   -0.130727  0.846263  ...                1.621871      0
4    0.065145  1.240352  ...               19.955523      1
..        ...       ...  ...                     ...    ...
456 -0.176294  1.212596  ...              121.367196      0
457 -0.661810  0.841780  ...               15.415169      1
458 -0.172682  0.684955  ...               46.585387      1
459 -0.128297  0.746526  ...               37.970923      0
460 -0.183494  0.869744  ...                1.185990      1

[461 rows x 798 columns]

#SBERT NLI Embeddings

In [9]:
#For BERT CLS Embeddings Model
x_train, x_test, y_train, y_test = train_test_split(bert_cls_embeddings_df.iloc[:,:-1].values, bert_cls_embeddings_df.iloc[:,-1].values, test_size=0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(403, 768)
(101, 768)
(403,)
(101,)


##SVM Classifier

In [10]:
# param_grid = {'C': [0.01, 0.1, 1, 10],
#               'gamma': [1,0.1],
#               'kernel': ['rbf','linear']}


# grid = GridSearchCV(SVC(),param_grid,verbose=10)
# grid.fit(x_train,y_train)
# print(grid.best_params_)

In [11]:
svm_clf = SVC(kernel='linear',C=0.01,gamma=1,verbose=True) ### Earlier C=1, gamma=0.01 gave 76% accuracy
svm_clf.fit(x_train,y_train)

[LibSVM]

SVC(C=0.01, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=True)

In [43]:
#Dumping the SVM Model
joblib.dump(svm_clf,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/bert_cls_embeddings.pkl")
svm_clf = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/bert_cls_embeddings.pkl")

In [44]:
print("\n\nAccuracy report: ")
predict = svm_clf.predict(x_test)
print(classification_report(predict,y_test))
print(np.unique(predict,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

           0       0.65      0.77      0.71        39
           1       0.84      0.74      0.79        62

    accuracy                           0.75       101
   macro avg       0.74      0.76      0.75       101
weighted avg       0.77      0.75      0.76       101

(array([0, 1]), array([39, 62]))


##Random Forest Classifier

In [44]:
#Applying Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=400).fit(x_train, y_train)

In [45]:
#Dumping the Random Forest Model
joblib.dump(rfc,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Random Forest/rfc_bert_cls_embeddings.pkl")
rfc = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Random Forest/rfc_bert_cls_embeddings.pkl")

In [46]:
print("\n\nAccuracy report: ")
predict_test = rfc.predict(x_test)
print(classification_report(predict_test,y_test))
print(np.unique(predict_test,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

           0       0.63      0.76      0.69        38
           1       0.84      0.73      0.78        63

    accuracy                           0.74       101
   macro avg       0.73      0.75      0.74       101
weighted avg       0.76      0.74      0.75       101

(array([0, 1]), array([38, 63]))


##One Vs All Classifier

In [47]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

clf = OneVsRestClassifier(SVC()).fit(x_train,y_train)

In [48]:
#Dumping the One Vs All Model
joblib.dump(clf,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/OneVsAll/onevsall_bert_cls_embeddings.pkl")
clf = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/OneVsAll/onevsall_bert_cls_embeddings.pkl")

In [49]:
outputs = clf.predict(x_test)
print(classification_report(y_test,outputs))
print("\n\nModel's Valid Distribution: ",np.unique(outputs,return_counts = True))

              precision    recall  f1-score   support

           0       0.81      0.65      0.72        46
           1       0.75      0.87      0.81        55

    accuracy                           0.77       101
   macro avg       0.78      0.76      0.76       101
weighted avg       0.78      0.77      0.77       101



Model's Valid Distribution:  (array([0, 1]), array([37, 64]))


##Neural Networks

In [62]:
from sklearn.neural_network import MLPClassifier

### 800 --> 30 --> 10 --> 2

mlp = MLPClassifier(hidden_layer_sizes = (30,10),activation='relu',max_iter=10000)
mlp.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(30, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=10000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [63]:
#Dumping the Multi Perceptron Model
joblib.dump(mlp,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Neural Network/nn_bert_cls_embeddings.pkl")
mlp = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Neural Network/nn_bert_cls_embeddings.pkl")

In [64]:
outputs = mlp.predict(x_test)
print(classification_report(y_test,outputs))
print("\n\nModel's Valid Distribution: ",np.unique(outputs,return_counts = True))

              precision    recall  f1-score   support

           0       0.75      0.59      0.66        46
           1       0.71      0.84      0.77        55

    accuracy                           0.72       101
   macro avg       0.73      0.71      0.71       101
weighted avg       0.73      0.72      0.72       101



Model's Valid Distribution:  (array([0, 1]), array([36, 65]))


#SBERT NLI Embeddings + Text

In [31]:
#For SBERT NLI Embeddings Model
x_train, x_test, y_train, y_test = train_test_split(bert_cls_embeddings_text_df.iloc[:,:-1].values, bert_cls_embeddings_text_df.iloc[:,-1].values, test_size=0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(392, 778)
(99, 778)
(392,)
(99,)


##SVM Classifier

In [13]:
svm_clf = SVC(kernel='rbf',C=0.01,gamma=1,verbose=True) ### # on C=10, gamma=0.0001, we get arount 71
svm_clf.fit(x_train,y_train)

[LibSVM]

SVC(C=0.01, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=True)

In [14]:
#Dumping the SVM Model
joblib.dump(svm_clf,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/bert_cls_embeddings_text.pkl")
svm_clf = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/bert_cls_embeddings_text.pkl")

In [15]:
print("\n\nAccuracy report: ")
predict = svm_clf.predict(x_test)
print(classification_report(predict,y_test))
print(np.unique(predict,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.63      0.77        99

    accuracy                           0.63        99
   macro avg       0.50      0.31      0.39        99
weighted avg       1.00      0.63      0.77        99

(array([1]), array([99]))


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##Random Forest Classifier

In [32]:
#Applying Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=400).fit(x_train, y_train)

In [33]:
#Dumping the Random Forest Model
joblib.dump(rfc,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Random Forest/rfc_bert_cls_embeddings_text.pkl")
rfc = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Random Forest/rfc_bert_cls_embeddings_text.pkl")

In [34]:
print("\n\nAccuracy report: ")
predict_test = rfc.predict(x_test)
print(classification_report(predict_test,y_test))
print(np.unique(predict_test,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

           0       0.62      0.70      0.66        33
           1       0.84      0.79      0.81        66

    accuracy                           0.76        99
   macro avg       0.73      0.74      0.73        99
weighted avg       0.77      0.76      0.76        99

(array([0, 1]), array([33, 66]))


##One Vs All Classifier

In [15]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

clf = OneVsRestClassifier(SVC()).fit(x_train,y_train)

In [16]:
#Dumping the One Vs All Model
joblib.dump(clf,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/OneVsAll/onevsall_bert_cls_embeddings_text.pkl")
clf = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/OneVsAll/onevsall_bert_cls_embeddings_text.pkl")

In [17]:
outputs = clf.predict(x_test)
print(classification_report(y_test,outputs))
print("\n\nModel's Valid Distribution: ",np.unique(outputs,return_counts = True))

              precision    recall  f1-score   support

           0       0.50      0.19      0.27        37
           1       0.65      0.89      0.75        62

    accuracy                           0.63        99
   macro avg       0.57      0.54      0.51        99
weighted avg       0.59      0.63      0.57        99



Model's Valid Distribution:  (array([0, 1]), array([14, 85]))


##Neural Networks

In [18]:
from sklearn.neural_network import MLPClassifier

### 800 --> 30 --> 10 --> 2

mlp = MLPClassifier(hidden_layer_sizes = (30,10),activation='relu',max_iter=10000)
mlp.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(30, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=10000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [19]:
#Dumping the Multi Perceptron Model
joblib.dump(mlp,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Neural Network/nn_bert_cls_embeddings_text.pkl")
mlp = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Neural Network/nn_bert_cls_embeddings_text.pkl")

In [20]:
outputs = mlp.predict(x_test)
print(classification_report(y_test,outputs))
print("\n\nModel's Valid Distribution: ",np.unique(outputs,return_counts = True))

              precision    recall  f1-score   support

           0       0.57      0.46      0.51        37
           1       0.71      0.79      0.75        62

    accuracy                           0.67        99
   macro avg       0.64      0.62      0.63        99
weighted avg       0.66      0.67      0.66        99



Model's Valid Distribution:  (array([0, 1]), array([30, 69]))


#SBERT + NLI + Embeddings + Text + User

In [75]:
#For SBERT NLI Embeddings Model
x_train, x_test, y_train, y_test = train_test_split(bert_cls_embeddings_text_user_df.iloc[:,:-1].values, bert_cls_embeddings_text_user_df.iloc[:,-1].values, test_size=0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(368, 797)
(93, 797)
(368,)
(93,)


In [61]:
svm_clf = SVC(kernel='rbf',C=0.01,gamma=1,verbose=True)
svm_clf.fit(x_train,y_train)

[LibSVM]

SVC(C=0.01, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=True)

In [62]:
#Dumping the SVM Model
joblib.dump(svm_clf,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/bert_cls_embeddings_text_user.pkl")
svm_clf = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/bert_cls_embeddings_text_user.pkl")

In [63]:
print("\n\nAccuracy report: ")
predict = svm_clf.predict(x_test)
print(classification_report(predict,y_test))
print(np.unique(predict,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.58      0.73        93

    accuracy                           0.58        93
   macro avg       0.50      0.29      0.37        93
weighted avg       1.00      0.58      0.73        93

(array([1]), array([93]))


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##Random Forest Classifier

In [28]:
#Applying Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=400).fit(x_train, y_train)

In [29]:
#Dumping the Random Forest Model
joblib.dump(rfc,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Random Forest/rfc_bert_cls_embeddings_text_user.pkl")
rfc = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Random Forest/rfc_bert_cls_embeddings_text_user.pkl")

In [30]:
print("\n\nAccuracy report: ")
predict_test = rfc.predict(x_test)
print(classification_report(predict_test,y_test))
print(np.unique(predict_test,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

           0       0.64      0.81      0.71        31
           1       0.89      0.77      0.83        62

    accuracy                           0.78        93
   macro avg       0.76      0.79      0.77        93
weighted avg       0.81      0.78      0.79        93

(array([0, 1]), array([31, 62]))


##One Vs All Classifier

In [76]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

clf = OneVsRestClassifier(SVC()).fit(x_train,y_train)

In [77]:
#Dumping the One Vs All Model
joblib.dump(clf,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/OneVsAll/onevsall_bert_cls_embeddings_text_user.pkl")
clf = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/OneVsAll/onevsall_bert_cls_embeddings_text_user.pkl")

In [78]:
outputs = clf.predict(x_test)
print(classification_report(y_test,outputs))
print("\n\nModel's Valid Distribution: ",np.unique(outputs,return_counts = True))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        39
           1       0.58      1.00      0.73        54

    accuracy                           0.58        93
   macro avg       0.29      0.50      0.37        93
weighted avg       0.34      0.58      0.43        93



Model's Valid Distribution:  (array([1]), array([93]))


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##Neural Networks

In [40]:
from sklearn.neural_network import MLPClassifier

### 800 --> 30 --> 10 --> 2

mlp = MLPClassifier(hidden_layer_sizes = (30,10),activation='relu',max_iter=10000)
mlp.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(30, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=10000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [41]:
#Dumping the Multi Perceptron Model
joblib.dump(mlp,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Neural Network/nn_bert_cls_embeddings_text_user.pkl")
mlp = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Neural Network/nn_bert_cls_embeddings_text_user.pkl")

In [42]:
outputs = mlp.predict(x_test)
print(classification_report(y_test,outputs))
print("\n\nModel's Valid Distribution: ",np.unique(outputs,return_counts = True))

              precision    recall  f1-score   support

           0       0.54      0.38      0.45        39
           1       0.63      0.76      0.69        54

    accuracy                           0.60        93
   macro avg       0.58      0.57      0.57        93
weighted avg       0.59      0.60      0.59        93



Model's Valid Distribution:  (array([0, 1]), array([28, 65]))


#Just with User Features

In [79]:
#For BERT CLS Embeddings Model
x_train, x_test, y_train, y_test = train_test_split(bert_cls_embeddings_text_user_df.iloc[:,768:-1].values, bert_cls_embeddings_text_user_df.iloc[:,-1].values, test_size=0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(368, 29)
(93, 29)
(368,)
(93,)


In [65]:
x_train[0]

array([3.02900000e+03, 1.69150000e+04, 2.65000000e+02, 2.64000000e+02,
       9.96226415e-01, 1.00000000e+01, 1.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.55000000e+02, 1.60000000e+01,
       1.10000000e+01, 4.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.08440000e+04, 1.38900000e+03, 2.66000000e+02, 1.65260000e+04,
       1.00000000e+00, 3.23900000e+03, 1.00000000e+00, 6.29670000e+04,
       0.00000000e+00, 1.94402593e+01, 0.00000000e+00, 2.62454937e-01,
       7.80705544e+00])

##SVM 

In [66]:
svm_clf = SVC(kernel='rbf',C=0.01,gamma=1,verbose=True)
svm_clf.fit(x_train,y_train)

[LibSVM]

SVC(C=0.01, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=True)

In [67]:
#Dumping the SVM Model
joblib.dump(svm_clf,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/svm_just_text_user.pkl")
svm_clf = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/svm_just_text_user.pkl")

In [68]:
print("\n\nAccuracy report: ")
predict = svm_clf.predict(x_test)
print(classification_report(predict,y_test))
print(np.unique(predict,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.58      0.73        93

    accuracy                           0.58        93
   macro avg       0.50      0.29      0.37        93
weighted avg       1.00      0.58      0.73        93

(array([1]), array([93]))


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##Random Forest Classifier

In [69]:
#Applying Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=400).fit(x_train, y_train)

In [70]:
#Dumping the Random Forest Model
joblib.dump(rfc,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Random Forest/rfc_just_text_user.pkl")
rfc = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Random Forest/rfc_just_text_user.pkl")

In [71]:
print("\n\nAccuracy report: ")
predict_test = rfc.predict(x_test)
print(classification_report(predict_test,y_test))
print(np.unique(predict_test,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

           0       0.59      0.68      0.63        34
           1       0.80      0.73      0.76        59

    accuracy                           0.71        93
   macro avg       0.69      0.70      0.70        93
weighted avg       0.72      0.71      0.71        93

(array([0, 1]), array([34, 59]))


##One Vs All Classifier

In [80]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

clf = OneVsRestClassifier(SVC()).fit(x_train,y_train)

In [81]:
#Dumping the One Vs All Model
joblib.dump(clf,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/OneVsAll/onevsall_just_text_user.pkl")
clf = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/OneVsAll/onevsall_just_text_user.pkl")

In [82]:
outputs = clf.predict(x_test)
print(classification_report(y_test,outputs))
print("\n\nModel's Valid Distribution: ",np.unique(outputs,return_counts = True))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        39
           1       0.58      1.00      0.73        54

    accuracy                           0.58        93
   macro avg       0.29      0.50      0.37        93
weighted avg       0.34      0.58      0.43        93



Model's Valid Distribution:  (array([1]), array([93]))


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##Neural Networks

In [83]:
from sklearn.neural_network import MLPClassifier

### 800 --> 30 --> 10 --> 2

mlp = MLPClassifier(hidden_layer_sizes = (5),activation='relu',max_iter=10000)
mlp.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=5, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=10000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [84]:
#Dumping the Multi Perceptron Model
joblib.dump(mlp,r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Neural Network/nn_just_text_user.pkl")
mlp = joblib.load(r"/gdrive/My Drive/2nd Sem/IBM/Covid Project/Models/Neural Network/nn_just_text_user.pkl")

In [85]:
outputs = mlp.predict(x_test)
print(classification_report(y_test,outputs))
print("\n\nModel's Valid Distribution: ",np.unique(outputs,return_counts = True))

              precision    recall  f1-score   support

           0       0.52      0.31      0.39        39
           1       0.61      0.80      0.69        54

    accuracy                           0.59        93
   macro avg       0.57      0.55      0.54        93
weighted avg       0.58      0.59      0.57        93



Model's Valid Distribution:  (array([0, 1]), array([23, 70]))
